### ISSUE TITLE
Default color

### ISSUE THREAD

**Issue by jaudiger** [nushell/nu-ansi-term#28]
Clippy starts to report the following issue:

```
warning: this `impl` can be derived
   --> src/style.rs:374:1
    |
374 | / impl Default for Color {
375 | |     fn default() -> Self {
376 | |         Color::White
377 | |     }
378 | | }
    | |_^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
    = note: `#[warn(clippy::derivable_impls)]` on by default
    = help: remove the manual implementation...
help: ...and instead derive it...
    |
288 | #[derive(Default)]
    |
help: ...and mark the default variant
    |
344 ~     #[default]
345 ~     White,
    |
```

The problem is: `nu_ansi_term::Color` contains an already defined `Color::Default` color, which is not used in the implementation of the trait `Default` for `nu_ansi_term::Color`:

```rust
impl Default for Color {
    fn default() -> Self {
        Color::White
    }
}
```

So, should we define Color::White or Color::Default inside `Default`?

**Comment by fdncred** [comment]
I think I'd vote for `Color::Default`. I'm sure that's just a left over from when I added `Color::Default` since the original code didn't have it. I just missed it here.

**Comment by jaudiger** [comment]
Ok, you can assign me to this issue. I'll do a PR later!

**Comment by fdncred** [comment]
> Ok, you can assign me to this issue. I'll do a PR later!

Done. Thanks!
