### ISSUE TITLE
Breaking change introduced by adding private field to transparent `Style` struct.

### ISSUE THREAD

**Issue by sholderbach** [nushell/nu-ansi-term#46]
See the test failure in https://github.com/sharkdp/lscolors/actions/runs/5187090829/jobs/9349029439

#43 added a `pub(crate)` field to `Style` which blocks outside consumers of the crate to manually construct `Style`.

https://github.com/nushell/nu-ansi-term/blob/98b763f432724d88f75906878f61341e4c52a944/src/style.rs#L24-L28

Previously this was possible as all fields were marked `pub` and the types accessible to the outside world.

Three possible courses of actions:
1. Embrace this breaking change and assume that `Style` shouldn't be built directly (and maybe hide all fields).
2. Accept a basic breaking change that introduces this field. Make `OSControl` public if necessary.\
3. Figure out a way to achieve the same behavior without modifying `Style`

I currently favor the latter two options as with the many crates around ANSI styling in the ecosystem e.g. owo-colors etc. being able to transparently convert the base style as another crate is valuable.

As a lesson learned we should probably add a test that constructs and destructures `Style` manually. This would make a breakage to the API a bit more obvious. (Also worth looking into tools like https://crates.io/crates/cargo-semver-checks)

**Comment by fdncred** [comment]
Dang, this just stinks. I really don't enjoy breaking everyone. Seems like we should figure out a way around this without breaking Style.

**Comment by mhelsley** [comment]
I agree -- I was trying to avoid breaking Style in the first place (the alternate implementation broke it by dropping the Copy trait) but clearly did not succeed.

> 2. Accept a basic breaking change that introduces this field. Make `OSControl` public if necessary.\
> 3. Figure out a way to achieve the same behavior without modifying `Style`
>
> I currently favor the latter two options as with the many crates around ANSI styling in the ecosystem e.g. owo-colors etc. being able to transparently convert the base style as another crate is valuable.

I think option 3 is the best and there might be a way to do it. I need to think about it some more though.

Considering that there's already a commit that breaks external code that manually constructs Style { .. } I wonder if it might be wiser to immediately revert PR #43 for now to minimize pain and buy time so I can try for option 3. I could also add the test case you mentioned.

**Comment by alexkunde** [comment]
@mhelsley what speaks against making the field just `pub` and adding a sensable default? that way, reconstruction is allowed and everyone using ..default:default() will not see a breaking change

**Comment by fdncred** [comment]
@alexkunde I could probably live with your suggestion. @sholderbach What do you think?

**Comment by mhelsley** [comment]
@alexkunde
`None` is indeed a sensible default. Also, it might be good to mention in the docs that using the update syntax (e.g. `..Default::default()` ) is recommended to future-proof manual creation of Style structs.

+ @sholderbach @fdncred

As for motivation for not using `pub` here:

I'm worried that exposing OSControl as part of the API might increase the likelihood of API users fiddling with it. That could introduce OSC sequences terminal emulators won't recognize or it might blow up the number of combinations nu-ansi-term will have to handle in the code in order to keep compatibility going forward. That's why my feeling is it would be preferable if there was some way to prevent code outside the crate from supplying anything except None in `.oscontrol`.

**Comment by mhelsley** [comment]
I put up a new RFC branch (add-osc-attempt2) in my fork showing what I think just the API changes would look like. For now it starts with reverting the original commit as a convenience to get this going quickly so folks can have a look.

It builds but is completely untested. I expect much of the test code will be very similar.

I even modeled state tracking for semantic prompt functionality. Though I'm unsure that I recall the states and transitions correctly it still shows how it might be used to constrain callers to ensure they comply with valid state transitions while giving some idea of what more complex OSC codes might need. The idea is each creating a new instance in a subsequent state requires the instance with the previous state and starting with the "prompt" or None state.

**Comment by sholderbach** [comment]
> I've written a test that manually constructs `Style` and would detect a future breaking change. However, I'm not sure I know what you had in mind for a destructuring test. I'm fairly new to Rust so I'm having a hard time imagining problems a destructuring test might uncover that a manual construction test would not. If you could show me a snippet of the destructuring I could add that test.

Yeah that should suffice for testing. I was thinking of extracting the fields through pattern matching in a `let` or `match` but that shouldn't help the test in any additional way.


> I don't think I understand your `termcap` reference in the context of validating things here. Do you have a link to an example of `termcap`-like checks you're referring to or perhaps some quick pseudocode?

There is on some systems (a) file(s) that could through cryptic codes describe what a terminal can or cannot do and how it is set up at the moment. See `man termcap` or `man terminfo` but that doesn't really translate on all platforms. Also it may not be faithfully implemented especially when we are dealing with a terminal where the availability of certain capabilities is in question.

> For the OSC sequences, so far, I've just modified the original `::hyperlink()`, `::title()`, `::icon()`, and `::cwd()` tests.

Awesome! Thanks

**Comment by sylvestre** [comment]
would it be possible to have a new release of nu-ansi-term with this change? 
(i already made the mistake of uploading lscolors & nu-ansi-term in debian)

**Comment by amtoine** [comment]
@sylvestre 
the next release of Nushell will be on the 25th of july, so i think `nu-ansi-term` will be released at the same time if there are new feature to include :blush: 

we switched to a 4-week schedule to buy us more time between releases towards 1.0 :relieved:

**Comment by sholderbach** [comment]
Sorry @amtoine, but what you are suggesting is simply unworkable as we use `nu-ansi-term` types to interface with third-party crates like `lscolors`. We will make `nu-ansi-term` releases with ample time before the Nushell releases to coordinate with the ecosystem, and only if necessary.

To your question @sylvestre, I will try to check a build of nushell (using `lscolors`) incorporating #47 and then make the release if nothing problematic pops up.

**Comment by fdncred** [comment]
Thanks @sholderbach. I agree. It's kind of a pain doing this. It looks to me like we'll need to release it so that `lscolors` can use the `with_reset` changes. I didn't look to see if there was a PR on `lscolors` for that yet. Maybe they're waiting on us?

**Comment by sholderbach** [comment]
Alright tested `nu` with `lscolors` and `reedline` using the new version. Everything still seems to work. The only breaking change which was expected was the `with_reset` field added to manual constructions (#40). (are we happy with the name?)
Have not changed the nushell link construction to directly use the new link support, that would be the final test.

**Comment by fdncred** [comment]
> are we happy with the name?

We could be more verbose like `starts_with_reset` but I'm not sure it's necessary. What do you think?

**Comment by sylvestre** [comment]
@sholderbach thanks, I appreciate it. This issue is preventing upgrades of the Rust/coreutils in Debian/Ubuntu :)
