### ISSUE TITLE
Derive frequently used traits

### ISSUE THREAD

**Issue by emmalexandria** [nushell/nu-ansi-term#57]
I'm writing a library making use of this project, and it would be hugely helpful if the types derived common traits like `PartialEq, Eq, Hash, Debug, Clone` etc (where possible). I'm happy to make a fork, but I think it would be generally good for the usability of the library.

**Comment by sholderbach** [comment]
Is there a particular type where you ran into a limitation? 
I think apart from `Hash` we should already be pretty consistenly implementing those.

**Comment by emmalexandria** [comment]
> Is there a particular type where you ran into a limitation? 
> I think apart from `Hash` we should already be pretty consistenly implementing those.

Sorry, that's why I closed it. I looked through the source code and realised I had pretty much hallucinated a lack of default impls. Thanks for responding though!
