### ISSUE TITLE
Request: hyperlink (HTML-like anchor)

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nu-ansi-term#6]
[How it looks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#quick-example).

---

Originally, I was waiting for [the main repo](https://github.com/ogham/rust-ansi-term) to implement [this feature](https://github.com/ogham/rust-ansi-term/issues/60), but it appears [unmaintained](https://github.com/ogham/rust-ansi-term/issues/72) and `nu-ansi-term` is the second most popular ANSI crate, so I open an issue here.

**Comment by sholderbach** [comment]
Good call! We have been manually doing that in nushell for a while. If it fits with the ansi-term API, we would definitely be happy to have that in this crate.

**Comment by sholderbach** [comment]
This has been implemented by #43
